#include <bits/stdc++.h>
#if __has_include(<atcoder/all>)
  #include <atcoder/all>
using namespace atcoder;
using mint = modint998244353;
#endif
using namespace std;
using ll = long long;
#define rep(i, n) for (ll i = 0; i < (n); ++i)
#define rep1(i, s, n) for (ll i = s; i < n; i++)
int main() {
    string l,r;
    cin >> l >> r;
    ll lsum=0,rsum=0;
    ll l2,r2;
    rep(i,l.size()){
        if(i==0){
            l2=l.at(i)-'0';
        }
        else{
            l2=l2*10+l.at(i)-'0';
        }
    }
    rep(i,r.size()){
        if(i==0){
            r2=r.at(i)-'0';
        }
        else{
            r2=r2*10+r.at(i)-'0';
        }
    }
    rep(i,r.size()){
        rep(j,10){
            rsum+=pow(j,i);
        }
    }
    rep(i,l.size()){
        rep(j,10){
            lsum+=pow(j,i);
        }
    }
    if(l.at(0)>=1){
        lsum+=pow(1,l.size());
    }
    if(l.at(0)>=2){
        lsum+=pow(2,l.size());
    }
    else{
        rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=3){
        lsum+=pow(3,l.size());
    }
    else{
        rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=4){
        lsum+=pow(4,l.size());
    }
    else{
        rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=5){
        lsum+=pow(5,l.size());
    }
    else{
        rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=6){
        lsum+=pow(6,l.size());
    }
    else{
        rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=7){
        lsum+=pow(7,l.size());
    }
    else{
        rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=8){
        lsum+=pow(8,l.size());
    }
    else{
    rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(l.at(0)>=9){
        lsum+=pow(9,l.size());
    }
    else{
    rep(i,l.size()-1){
            if(l.at(i+1)>=1){
                lsum+=pow(1,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=2){
                lsum+=pow(2,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=3){
                lsum+=pow(3,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=4){
                lsum+=pow(4,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=5){
                lsum+=pow(5,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=6){
                lsum+=pow(6,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=7){
                lsum+=pow(7,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=8){
                lsum+=pow(8,l.size()-i-1);
            }
            else{
                continue;
            }
            if(l.at(i+1)>=9){
                lsum+=pow(9,l.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=1){
        rsum+=pow(1,r.size());
    }
    if(r.at(0)>=2){
        rsum+=pow(2,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=3){
        rsum+=pow(3,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=4){
        rsum+=pow(4,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=5){
        rsum+=pow(5,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=6){
        rsum+=pow(6,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=7){
        rsum+=pow(7,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=8){
        rsum+=pow(8,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    if(r.at(0)>=9){
        rsum+=pow(9,r.size());
    }
    else{
        rep(i,r.size()-1){
            if(r.at(i+1)>=1){
                lsum+=pow(1,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=2){
                lsum+=pow(2,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=3){
                lsum+=pow(3,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=4){
                lsum+=pow(4,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=5){
                lsum+=pow(5,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=6){
                lsum+=pow(6,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=7){
                lsum+=pow(7,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=8){
                lsum+=pow(8,r.size()-i-1);
            }
            else{
                continue;
            }
            if(r.at(i+1)>=9){
                lsum+=pow(9,r.size()-i-1);
            }
            else{
                continue;
            }
        }
    }
    cout << rsum-lsum << endl;
}